name: webrtcvideocall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  crypto: ^3.0.3
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.1
  shared_preferences: ^2.2.3
  socket_io_client: ^3.0.0-beta.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
