// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadat1FWbvnU1_Wu4fZBxQlyNAyWjQkIM',
    appId: '1:2405654849:web:4f4360cbdb75fe44ec01c0',
    messagingSenderId: '2405654849',
    projectId: 'vi-deo-call',
    authDomain: 'vi-deo-call.firebaseapp.com',
    storageBucket: 'vi-deo-call.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3OEyjU8RUKbNCwFYQmeYCNUNpRHUvCU',
    appId: '1:2405654849:android:7c3276f8fa9b5319ec01c0',
    messagingSenderId: '2405654849',
    projectId: 'vi-deo-call',
    storageBucket: 'vi-deo-call.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGsMpFdQ9WKm5S6N2arLr0xqTyiQ_LJ-Q',
    appId: '1:2405654849:ios:81cb414078ae456eec01c0',
    messagingSenderId: '2405654849',
    projectId: 'vi-deo-call',
    storageBucket: 'vi-deo-call.appspot.com',
    iosBundleId: 'com.example.webrtcvideocall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGsMpFdQ9WKm5S6N2arLr0xqTyiQ_LJ-Q',
    appId: '1:2405654849:ios:81cb414078ae456eec01c0',
    messagingSenderId: '2405654849',
    projectId: 'vi-deo-call',
    storageBucket: 'vi-deo-call.appspot.com',
    iosBundleId: 'com.example.webrtcvideocall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDadat1FWbvnU1_Wu4fZBxQlyNAyWjQkIM',
    appId: '1:2405654849:web:95192c48926f4dffec01c0',
    messagingSenderId: '2405654849',
    projectId: 'vi-deo-call',
    authDomain: 'vi-deo-call.firebaseapp.com',
    storageBucket: 'vi-deo-call.appspot.com',
  );
}
